#!/usr/bin/env bash
# Build Orbit Edge images and write digest pins to images.lock + compose.images.yaml
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [[ ! -f .env ]]; then
  echo "Copy .env.example to .env and set JWT_SECRET first." >&2
  exit 1
fi

echo "Building images..."
docker compose --env-file .env build

pin() {
  local service="$1"
  local image
  image="$(docker compose --env-file .env images -q "$service" | head -1)"
  if [[ -z "$image" ]]; then
    echo "No image for service $service" >&2
    exit 1
  fi
  local digest
  digest="$(docker image inspect "$image" --format '{{index .RepoDigests 0}}' 2>/dev/null || true)"
  if [[ -z "$digest" || "$digest" == "<no value>" ]]; then
    # Local build may lack registry digest — pin by image ID
    digest="$(docker image inspect "$image" --format '{{.Id}}')"
  fi
  echo "$service $digest"
}

{
  echo "# Generated by scripts/pin-images.sh — $(date -u +%Y-%m-%dT%H:%MZ)"
  echo "# Use with: docker compose -f compose.yaml -f compose.images.yaml up -d"
  echo
  auth_id="$(docker compose --env-file .env images -q auth | head -1)"
  notif_id="$(docker compose --env-file .env images -q notifications | head -1)"
  gw_id="$(docker compose --env-file .env images -q gateway | head -1)"
  echo "ORBIT_AUTH_IMAGE=$(docker image inspect "$auth_id" --format '{{.Id}}')"
  echo "ORBIT_NOTIFICATIONS_IMAGE=$(docker image inspect "$notif_id" --format '{{.Id}}')"
  echo "ORBIT_GATEWAY_IMAGE=$(docker image inspect "$gw_id" --format '{{.Id}}')"
} | tee images.lock

# Base images digests (best-effort after pull)
{
  echo "# Generated by scripts/pin-images.sh — $(date -u +%Y-%m-%dT%H:%MZ)"
  echo "services:"
  for svc in postgres redis mailpit; do
    img="$(docker compose --env-file .env images -q "$svc" 2>/dev/null | head -1 || true)"
    if [[ -n "$img" ]]; then
      id="$(docker image inspect "$img" --format '{{.Id}}')"
      echo "  $svc:"
      echo "    image: $id"
    fi
  done
} > compose.images.yaml

echo "Wrote images.lock and compose.images.yaml"
echo "Rollback: check out a previous git tag of this repo (or restore images.lock) and:"
echo "  docker compose --env-file .env -f compose.yaml --env-file images.lock up -d"
